apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: hello-embedded-taskrun-
spec:
  taskSpec:
    steps:
      - name: step-1
        image: busybox:latest
        script: |
          echo "Hello from step 1"
