apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-local-registry
spec:
  steps:
    - name: echo
      image: localhost:5000/my-busybox
      script: |
        #!/bin/sh
        echo "Hello Busybox from local registry!"
